

export const CityData = {
    Vinnytsia: {
      streets: [
        {name:'V.Antonovycha',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Barvysta',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Berehova',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Bohomolʹtsya',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Botanichna',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      ],
    },
    Dnipro: {
      streets: [
        {name:'Aviatsiyna',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Barykadna',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Vynohradna',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Donetsʹke shose',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],},
        {name:'Enerhetychna',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      ],
 
    },

    Kyiv: {
      streets: [
        {name:'Berehova',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Desyatynna',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Kvitucha',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Kyyivsʹka',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Medychna',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Mezhyhirsʹka',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      ],
  
    },
    Odesa: {
      streets: [
        {name:'Abrykosova',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Bazarna',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Varnensʹka',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Hazova',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
        {name:'Naftovykiv',
        houseNumbers: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      ],
    },
  };
  
  

  export const getStreets = city => {
    if (CityData[city]) {
      return CityData[city].streets.map(street => street.name);
    }
    return []; // Возвращаем пустой массив, если город не найден
  };
  
  export const getHouseNumbersForStreet = (city, streetName) => {
    if (CityData[city]) {
      const street = CityData[city].streets.find(s => s.name === streetName);
      const houseNumbers = street ? street.houseNumbers : [];
      return houseNumbers;
     
    }
    return []; 
  };


